// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { UniversalRouterParams } from "./../index.sol";
import { ResourceId } from "@latticexyz/world/src/WorldResourceId.sol";

/**
 * @title IRouterSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRouterSystem {
  function universalRouterExecute(
    UniversalRouterParams[] calldata routerExecuteParams,
    ResourceId fromNamespaceId
  ) external payable;
}
