// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBonusSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBonusSystem {
  function popCraft_BonusSystem_getUserBenefitsToken() external;
}
