// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { UniversalRouterParams } from "./../../core_codegen/index.sol";

/**
 * @title IBuySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBuySystem {
  function popCraft_BuySystem_buyToken(UniversalRouterParams[] calldata universalRouterParams) external payable;
}
