// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ExchangeGpTokenData } from "./../../libraries/Struct.sol";

/**
 * @title IExchangeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IExchangeSystem {
  function popCraft_ExchangeSystem_gpExchangeToken(ExchangeGpTokenData[] memory exchangeGpTokenData) external;

  function popCraft_ExchangeSystem_getPlantsGp(address player) external view returns (uint256);
}
