// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IInviteSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInviteSystem {
  function popCraft_InviteSystem_genInviteCode() external;

  function popCraft_InviteSystem_acceptInvitation(bytes8 code) external;
}
