// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IMClearBoardSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMClearBoardSystem {
  function popCraft_MClearBoardSyste_pop(DefaultParameters memory default_parameters) external;

  function popCraft_MClearBoardSyste_checkGameSuccess(uint256[] memory matrix_array) external pure returns (bool);
}
