// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMissionSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMissionSystem {
  function popCraft_MissionSystem_getDailyGamesRewards() external;
}
