// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IModeScoreChallengeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IModeScoreChallengeSystem {
  function popCraft_ModeScoreChallen_pop(DefaultParameters memory default_parameters) external;

  function popCraft_ModeScoreChallen_checkGameSuccess(
    address owner,
    uint256 eliminateScore
  ) external view returns (bool);

  function popCraft_ModeScoreChallen_regenerateBottomRows(
    address player,
    uint256[] memory board
  ) external returns (uint256[] memory);
}
