// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IMScoreChallengeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMScoreChallengeSystem {
  function popCraft_MScoreChallengeS_pop(DefaultParameters memory default_parameters) external;

  function popCraft_MScoreChallengeS_checkGameSuccess(
    address owner,
    uint256 eliminateScore
  ) external view returns (bool);
}
