// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlantsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlantsSystem {
  function popCraft_PlantsSystem_collectSeed() external;

  function popCraft_PlantsSystem_grow() external;
}
