// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IPopCraftSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPopCraftSystem {
  error InsufficientBalance(address);

  function popCraft_PopCraftSystem_interact(DefaultParameters memory default_parameters) external;

  function popCraft_PopCraftSystem_pop(DefaultParameters memory default_parameters) external;
}
