// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters, UniversalRouterParams } from "./../../core_codegen/index.sol";

/**
 * @title IPopCraftSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPopCraftSystem {
  error InsufficientBalance(address);
  error Inventory_shortage(address shortageToken);
  error GetQuoteError();
  error GameContinues();
  error ExceededPurchaseLimit(uint256 limit);

  function popCraft_PopCraftSystem_init() external;

  function popCraft_PopCraftSystem_interact(DefaultParameters memory default_parameters) external;

  function popCraft_PopCraftSystem_pop(DefaultParameters memory default_parameters) external;

  function popCraft_PopCraftSystem_buyToken(UniversalRouterParams[] calldata universalRouterParams) external payable;

  function popCraft_PopCraftSystem_reIssuanceRewards(address[] memory owner) external;
}
