// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IBonusSystem } from "./IBonusSystem.sol";
import { IBuySystem } from "./IBuySystem.sol";
import { IExchangeSystem } from "./IExchangeSystem.sol";
import { IInviteSystem } from "./IInviteSystem.sol";
import { IMClearBoardSystem } from "./IMClearBoardSystem.sol";
import { IMissionSystem } from "./IMissionSystem.sol";
import { IMScoreChallengeSystem } from "./IMScoreChallengeSystem.sol";
import { IPlantsSystem } from "./IPlantsSystem.sol";
import { IPopCraftSystem } from "./IPopCraftSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IBonusSystem,
  IBuySystem,
  IExchangeSystem,
  IInviteSystem,
  IMClearBoardSystem,
  IMissionSystem,
  IMScoreChallengeSystem,
  IPlantsSystem,
  IPopCraftSystem
{

}
