// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IPopStarSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPopStarSystem {
  function popStar_PopStarSystem_init() external;

  function popStar_PopStarSystem_interact(DefaultParameters memory default_parameters) external;

  function popStar_PopStarSystem_pop(DefaultParameters memory default_parameters) external;
}
