// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { DefaultParameters } from "./../../core_codegen/index.sol";

/**
 * @title IPuzzleSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPuzzleSystem {
  function puzzle_PuzzleSystem_init() external;

  function puzzle_PuzzleSystem_interact(DefaultParameters memory default_parameters) external;

  function puzzle_PuzzleSystem_move(DefaultParameters memory default_parameters) external;
}
