// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14("popStar"), bytes16("PopStar")))
);
ResourceId constant PopStarTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0009030104040100000000000000000000000000000000000000000000000000
);

struct PopStarData {
  uint32 x;
  uint32 y;
  bool gameFinished;
  uint256[] matrixArray;
}

library PopStar {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](3);
    _keySchema[0] = SchemaType.UINT256;
    _keySchema[1] = SchemaType.ADDRESS;
    _keySchema[2] = SchemaType.BYTES32;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](4);
    _valueSchema[0] = SchemaType.UINT32;
    _valueSchema[1] = SchemaType.UINT32;
    _valueSchema[2] = SchemaType.BOOL;
    _valueSchema[3] = SchemaType.UINT256_ARRAY;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "timestamp";
    keyNames[1] = "owner";
    keyNames[2] = "app";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "x";
    fieldNames[1] = "y";
    fieldNames[2] = "gameFinished";
    fieldNames[3] = "matrixArray";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get x.
   */
  function getX(uint256 timestamp, address owner, bytes32 app) internal view returns (uint32 x) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get x.
   */
  function _getX(uint256 timestamp, address owner, bytes32 app) internal view returns (uint32 x) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set x.
   */
  function setX(uint256 timestamp, address owner, bytes32 app, uint32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Set x.
   */
  function _setX(uint256 timestamp, address owner, bytes32 app, uint32 x) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((x)), _fieldLayout);
  }

  /**
   * @notice Get y.
   */
  function getY(uint256 timestamp, address owner, bytes32 app) internal view returns (uint32 y) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get y.
   */
  function _getY(uint256 timestamp, address owner, bytes32 app) internal view returns (uint32 y) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set y.
   */
  function setY(uint256 timestamp, address owner, bytes32 app, uint32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((y)), _fieldLayout);
  }

  /**
   * @notice Set y.
   */
  function _setY(uint256 timestamp, address owner, bytes32 app, uint32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((y)), _fieldLayout);
  }

  /**
   * @notice Get gameFinished.
   */
  function getGameFinished(uint256 timestamp, address owner, bytes32 app) internal view returns (bool gameFinished) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get gameFinished.
   */
  function _getGameFinished(uint256 timestamp, address owner, bytes32 app) internal view returns (bool gameFinished) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set gameFinished.
   */
  function setGameFinished(uint256 timestamp, address owner, bytes32 app, bool gameFinished) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((gameFinished)), _fieldLayout);
  }

  /**
   * @notice Set gameFinished.
   */
  function _setGameFinished(uint256 timestamp, address owner, bytes32 app, bool gameFinished) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((gameFinished)), _fieldLayout);
  }

  /**
   * @notice Get matrixArray.
   */
  function getMatrixArray(
    uint256 timestamp,
    address owner,
    bytes32 app
  ) internal view returns (uint256[] memory matrixArray) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get matrixArray.
   */
  function _getMatrixArray(
    uint256 timestamp,
    address owner,
    bytes32 app
  ) internal view returns (uint256[] memory matrixArray) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set matrixArray.
   */
  function setMatrixArray(uint256 timestamp, address owner, bytes32 app, uint256[] memory matrixArray) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((matrixArray)));
  }

  /**
   * @notice Set matrixArray.
   */
  function _setMatrixArray(uint256 timestamp, address owner, bytes32 app, uint256[] memory matrixArray) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((matrixArray)));
  }

  /**
   * @notice Get the length of matrixArray.
   */
  function lengthMatrixArray(uint256 timestamp, address owner, bytes32 app) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of matrixArray.
   */
  function _lengthMatrixArray(uint256 timestamp, address owner, bytes32 app) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of matrixArray.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemMatrixArray(
    uint256 timestamp,
    address owner,
    bytes32 app,
    uint256 _index
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of matrixArray.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemMatrixArray(
    uint256 timestamp,
    address owner,
    bytes32 app,
    uint256 _index
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to matrixArray.
   */
  function pushMatrixArray(uint256 timestamp, address owner, bytes32 app, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to matrixArray.
   */
  function _pushMatrixArray(uint256 timestamp, address owner, bytes32 app, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from matrixArray.
   */
  function popMatrixArray(uint256 timestamp, address owner, bytes32 app) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from matrixArray.
   */
  function _popMatrixArray(uint256 timestamp, address owner, bytes32 app) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of matrixArray at `_index`.
   */
  function updateMatrixArray(uint256 timestamp, address owner, bytes32 app, uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of matrixArray at `_index`.
   */
  function _updateMatrixArray(
    uint256 timestamp,
    address owner,
    bytes32 app,
    uint256 _index,
    uint256 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 timestamp, address owner, bytes32 app) internal view returns (PopStarData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 timestamp, address owner, bytes32 app) internal view returns (PopStarData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 timestamp,
    address owner,
    bytes32 app,
    uint32 x,
    uint32 y,
    bool gameFinished,
    uint256[] memory matrixArray
  ) internal {
    bytes memory _staticData = encodeStatic(x, y, gameFinished);

    PackedCounter _encodedLengths = encodeLengths(matrixArray);
    bytes memory _dynamicData = encodeDynamic(matrixArray);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 timestamp,
    address owner,
    bytes32 app,
    uint32 x,
    uint32 y,
    bool gameFinished,
    uint256[] memory matrixArray
  ) internal {
    bytes memory _staticData = encodeStatic(x, y, gameFinished);

    PackedCounter _encodedLengths = encodeLengths(matrixArray);
    bytes memory _dynamicData = encodeDynamic(matrixArray);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 timestamp, address owner, bytes32 app, PopStarData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.x, _table.y, _table.gameFinished);

    PackedCounter _encodedLengths = encodeLengths(_table.matrixArray);
    bytes memory _dynamicData = encodeDynamic(_table.matrixArray);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 timestamp, address owner, bytes32 app, PopStarData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.x, _table.y, _table.gameFinished);

    PackedCounter _encodedLengths = encodeLengths(_table.matrixArray);
    bytes memory _dynamicData = encodeDynamic(_table.matrixArray);

    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint32 x, uint32 y, bool gameFinished) {
    x = (uint32(Bytes.slice4(_blob, 0)));

    y = (uint32(Bytes.slice4(_blob, 4)));

    gameFinished = (_toBool(uint8(Bytes.slice1(_blob, 8))));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    PackedCounter _encodedLengths,
    bytes memory _blob
  ) internal pure returns (uint256[] memory matrixArray) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    matrixArray = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    PackedCounter _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (PopStarData memory _table) {
    (_table.x, _table.y, _table.gameFinished) = decodeStatic(_staticData);

    (_table.matrixArray) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 timestamp, address owner, bytes32 app) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 timestamp, address owner, bytes32 app) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint32 x, uint32 y, bool gameFinished) internal pure returns (bytes memory) {
    return abi.encodePacked(x, y, gameFinished);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(uint256[] memory matrixArray) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(matrixArray.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(uint256[] memory matrixArray) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((matrixArray)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 x,
    uint32 y,
    bool gameFinished,
    uint256[] memory matrixArray
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(x, y, gameFinished);

    PackedCounter _encodedLengths = encodeLengths(matrixArray);
    bytes memory _dynamicData = encodeDynamic(matrixArray);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 timestamp, address owner, bytes32 app) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = bytes32(uint256(timestamp));
    _keyTuple[1] = bytes32(uint256(uint160(owner)));
    _keyTuple[2] = app;

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
