// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TCMPopStar, TCMPopStarData, TCMPopStarTableId } from "./tables/TCMPopStar.sol";
import { TokenBalance, TokenBalanceTableId } from "./tables/TokenBalance.sol";
import { TokenSold, TokenSoldData, TokenSoldTableId } from "./tables/TokenSold.sol";
import { GameRecord, GameRecordData, GameRecordTableId } from "./tables/GameRecord.sol";
import { StarToScore, StarToScoreTableId } from "./tables/StarToScore.sol";
import { DayToScore, DayToScoreTableId } from "./tables/DayToScore.sol";
import { RankingRecord, RankingRecordData, RankingRecordTableId } from "./tables/RankingRecord.sol";
import { Token, TokenTableId } from "./tables/Token.sol";
import { OverTime, OverTimeTableId } from "./tables/OverTime.sol";
import { GameRecordEvent, GameRecordEventData, GameRecordEventTableId } from "./tables/GameRecordEvent.sol";
import { GameFailedRecord, GameFailedRecordTableId } from "./tables/GameFailedRecord.sol";
import { Plants, PlantsData, PlantsTableId } from "./tables/Plants.sol";
import { TotalPlants, TotalPlantsTableId } from "./tables/TotalPlants.sol";
import { PlantsLevel, PlantsLevelData, PlantsLevelTableId } from "./tables/PlantsLevel.sol";
import { PlayerPlantingRecord, PlayerPlantingRecordData, PlayerPlantingRecordTableId } from "./tables/PlayerPlantingRecord.sol";
import { CurrentPlayerPlants, CurrentPlayerPlantsData, CurrentPlayerPlantsTableId } from "./tables/CurrentPlayerPlants.sol";
