// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TCMPopStar, TCMPopStarData, TCMPopStarTableId } from "./tables/TCMPopStar.sol";
import { TokenBalance, TokenBalanceTableId } from "./tables/TokenBalance.sol";
import { TokenSold, TokenSoldData, TokenSoldTableId } from "./tables/TokenSold.sol";
import { GameRecord, GameRecordData, GameRecordTableId } from "./tables/GameRecord.sol";
import { StarToScore, StarToScoreTableId } from "./tables/StarToScore.sol";
import { DayToScore, DayToScoreTableId } from "./tables/DayToScore.sol";
import { RankingRecord, RankingRecordData, RankingRecordTableId } from "./tables/RankingRecord.sol";
import { Token, TokenTableId } from "./tables/Token.sol";
import { PriTokenPrice, PriTokenPriceTableId } from "./tables/PriTokenPrice.sol";
import { OverTime, OverTimeTableId } from "./tables/OverTime.sol";
import { UserBenefitsToken, UserBenefitsTokenTableId } from "./tables/UserBenefitsToken.sol";
import { ComboReward, ComboRewardTableId } from "./tables/ComboReward.sol";
import { ComboRewardGames, ComboRewardGamesData, ComboRewardGamesTableId } from "./tables/ComboRewardGames.sol";
import { SeasonTime, SeasonTimeData, SeasonTimeTableId } from "./tables/SeasonTime.sol";
import { CurrentSeasonDimension, CurrentSeasonDimensionTableId } from "./tables/CurrentSeasonDimension.sol";
import { WeeklyRecord, WeeklyRecordData, WeeklyRecordTableId } from "./tables/WeeklyRecord.sol";
import { SeasonPlantsRecord, SeasonPlantsRecordTableId } from "./tables/SeasonPlantsRecord.sol";
import { ScoreToPointsRewards, ScoreToPointsRewardsTableId } from "./tables/ScoreToPointsRewards.sol";
import { ScoreToPoints, ScoreToPointsTableId } from "./tables/ScoreToPoints.sol";
import { DailyGames, DailyGamesData, DailyGamesTableId } from "./tables/DailyGames.sol";
import { StreakDays, StreakDaysData, StreakDaysTableId } from "./tables/StreakDays.sol";
import { GamesRewardsScores, GamesRewardsScoresTableId } from "./tables/GamesRewardsScores.sol";
import { NFTToTokenDiscount, NFTToTokenDiscountTableId } from "./tables/NFTToTokenDiscount.sol";
import { NFTRewards, NFTRewardsData, NFTRewardsTableId } from "./tables/NFTRewards.sol";
import { MorphBlack, MorphBlackData, MorphBlackTableId } from "./tables/MorphBlack.sol";
import { MorphBlackRewards, MorphBlackRewardsData, MorphBlackRewardsTableId } from "./tables/MorphBlackRewards.sol";
import { InviterV2, InviterV2Data, InviterV2TableId } from "./tables/InviterV2.sol";
import { InviteCodeToInviter, InviteCodeToInviterTableId } from "./tables/InviteCodeToInviter.sol";
import { PlayerToInviteV2, PlayerToInviteV2Data, PlayerToInviteV2TableId } from "./tables/PlayerToInviteV2.sol";
import { InvitationScoreRecord, InvitationScoreRecordData, InvitationScoreRecordTableId } from "./tables/InvitationScoreRecord.sol";
import { Plants, PlantsData, PlantsTableId } from "./tables/Plants.sol";
import { TotalPlants, TotalPlantsTableId } from "./tables/TotalPlants.sol";
import { PlantsLevel, PlantsLevelData, PlantsLevelTableId } from "./tables/PlantsLevel.sol";
import { PlayerPlantingRecord, PlayerPlantingRecordData, PlayerPlantingRecordTableId } from "./tables/PlayerPlantingRecord.sol";
import { CurrentPlayerPlants, CurrentPlayerPlantsData, CurrentPlayerPlantsTableId } from "./tables/CurrentPlayerPlants.sol";
